/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
void SysClockConfig(void)
{
	// 1. Cấu hình HSE và chờ cho HSE sẵn sàng
	RCC->CR |= RCC_CR_HSEON;
	while (!(RCC->CR & RCC_CR_HSERDY));
	// 2. Cài đặt POWER ENABLE CLOCK
	RCC->APB1ENR != RCC_APB1ENR_PWREN;
	// 3. Cấu hình FLASH PREFETCH and the LATENCY Realated Settings
	FLASH->ACR	|= FLASH_ACR_PRFTBE | FLASH_ACR_LATENCY_2;
	// 4.Cấu hình PRESCALARS HCLK, PCLK1, PCLK2
	// AHB PR
	RCC->CFGR |= RCC_CFGR_HPRE_DIV1;
	// APB1 PR
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;
	// APB2 PR
	RCC->CFGR |= RCC_CFGR_PPRE2_DIV1;
	// 5. Cấu hình PLL
	RCC->CFGR |= RCC_CFGR_PLLSRC;
	RCC->CFGR |= RCC_CFGR_PLLMULL9;
	// 6.Bật PLL và chờ sẵn sàng
	RCC->CFGR |= RCC_CR_PLLON;
	while(!(RCC->CR & RCC_CR_PLLRDY));
}

int main(void)
{
    while(1)
    {

    }
}
